"use strict"
const baseball = [{qid: cuid(),
				  question: "Which team has won the most World Series title?",
				  answers: [{aid: cuid(), answer: "New York Yankees", correct: true},
				            {aid: cuid(), answer: "Chicago White Sox", correct: false},
							{aid: cuid(), answer: "Toronto Blue Jays", correct: false},
							{aid: cuid(), answer: "Atlanta Braves", correct: false}],
				  response: "The New York Yankees have won 27 World Series titles.  Next comes the St Louis Cardinals who have won 11 followed by the Boston Red Sox with 9."},
				  {qid: cuid(),
				  question: "What famous baseball player said, \"It ain't over 'til it's over.\"",
				  answers: [{aid: cuid(), answer: "Yogi Berra", correct: true},
				            {aid: cuid(), answer: "Hank Aaron", correct: false},
							{aid: cuid(), answer: "Josh Gibson", correct: false},
							{aid: cuid(), answer: "Johnny Damon", correct: false}],
				  response: "Berra-isms (colloquial expressions that lack logic) are now countless, and many of them are just attributed to Yogi Berra, even if he never actually said them. As he so perfectly put it: \“I never said most of the things I said.\” <ul>Here are some others: <li>When you come to a fork in the road, take it.</li><li>You can observe a lot by just watching.</li><li>It’s like déjà vu all over again.</li><li>No one goes there nowadays, it’s too crowded.</li><li>Baseball is 90% mental and the other half is physical.</li><li>A nickel ain’t worth a dime anymore.</li><li>Always go to other people’s funerals, otherwise they won’t come to yours.</li></ul>"},
				  {qid: cuid(),
				  question: "Where is the Baseball Hall of Fame and National Museum located?",
				  answers: [{aid: cuid(), answer: "Cooperstown New York", correct: true},
				            {aid: cuid(), answer: "Baltimore Maryland", correct: false},
							{aid: cuid(), answer: "Cleveland Ohio", correct: false},
							{aid: cuid(), answer: "Louisville Kentucky", correct: false}],
				  response: "Cooperstown is a baseball hub for both fans of professional baseball and younger teams alike. The National Baseball Hall of Fame and Museum is an American history museum operated by private interests. As of 2018, 323 players have been elected to the Hall of Fame."},
				  {qid: cuid(),
				  question: "The Red Sox sold Babe Ruth to what team in 1920?",
				  answers: [{aid: cuid(), answer: "New York Yankees", correct: true},
				            {aid: cuid(), answer: "Los Angeles Angels", correct: false},
							{aid: cuid(), answer: "Brooklyn Dodgers", correct: false},
							{aid: cuid(), answer: "Washington Senators", correct: false}],
				  response: "The New York Yankees bought the Babe, and many baseball fans believe the sale of Babe Ruth created a curse, called the \"Curse of the Bambino,\" that prevented the Red Sox from winning a World Series. The \"curse\" was finally reversed in 2004."},
				  {qid: cuid(),
				  question: "What father-son pair was the only to play in the major leagues at the same time?",
				  answers: [{aid: cuid(), answer: "Ken Griffey Jr and Ken Griffey Sr", correct: true},
				            {aid: cuid(), answer: "Barry and Bobby Bonds", correct: false},
							{aid: cuid(), answer: "Tito and Terry Francona", correct: false},
							{aid: cuid(), answer: "Dale and Yogi Berra", correct: false}],
				  response: "Ken Griffey Jr and Ken Griffey Sr played at the same time, more than that they were the only father and son to play on the same team.  On September 14th, 1990, Ken Griffey Sr. hit a home run. His son, Ken Griffey Jr. stepped up to the plate next and followed up his father with his own long ball. The two became the first father and son to hit a home run in the same game."},
				  {qid: cuid(),
				  question: "Who was the only pitcher to pitch a perfect game in a World Series?",
				  answers: [{aid: cuid(), answer: "Don Larsen", correct: true},
				            {aid: cuid(), answer: "David Wells", correct: false},
							{aid: cuid(), answer: "Sandy Koufax", correct: false},
							{aid: cuid(), answer: "Dennis Martinez", correct: false}],
				  response: "Don Larsen of the New York Yankees pitched a perfect game during the 1956 World Series."},
				  {qid: cuid(),
				  question: "Who was the first African American baseball player to play in the modern major leagues?",
				  answers: [{aid: cuid(), answer: "Jackie Robinson", correct: true},
				            {aid: cuid(), answer: "Buck Leonard", correct: false},
							{aid: cuid(), answer: "Willie Mays", correct: false},
							{aid: cuid(), answer: "Satchel Paige", correct: false}],
				  response: "Jackie Robinson broke the baseball color line when he started at first base for the Brooklyn Dodgers on April 15, 1947.  He opened the door for many others and will forever be appreciated for his contribution to the game.  \“A life is not important except in the impact it has on other lives.\""},
				  {qid: cuid(),
				  question: "What player drew the Hebrew word \"Chai\" in the batter's box before each at-bat?",
				  answers: [{aid: cuid(), answer: "Wade Bogg", correct: true},
				            {aid: cuid(), answer: "Hank Greenberg", correct: false},
							{aid: cuid(), answer: "Ian Kinsler", correct: false},
							{aid: cuid(), answer: "Mike Liberthal", correct: false}],
				  response: "Wade Boggs was known for his superstitions. He ate chicken before every game, took exactly 117 ground balls in pre-game practice, and drew the Hebrew word \"Chai\", meaning \"life\", in the batter's box before each at-bat, though he was not Jewish."},
				  {qid: cuid(),
				  question: "What player holds the all time record number of hits?",
				  answers: [{aid: cuid(), answer: "Pete Rose", correct: true},
				            {aid: cuid(), answer: "Mark McGwire", correct: false},
							{aid: cuid(), answer: "Sammy Sosa", correct: false},
							{aid: cuid(), answer: "Alex Rodriquez", correct: false}],
				  response: "Pete Rose logged 4256 hits in his career.  Next comes Ty Cobbs with 4191.  They are the only two players with more than 4000 career hits."},
				  {qid: cuid(),
				  question: "What player has won the most MVP awards?",
				  answers: [{aid: cuid(), answer: "Barry Bonds", correct: true},
				            {aid: cuid(), answer: "Stan Musial", correct: false},
							{aid: cuid(), answer: "David Ortiz", correct: false},
							{aid: cuid(), answer: "Lou Gehrig", correct: false}],
				  response: "Barry Bonds has won four National League MVP Awards.  Several American League players have won three titles."},
				  {qid: cuid(),
				  question: "Who was the first Major League player to pitch a ball over 100 mph?",
				  answers: [{aid: cuid(), answer: "Nolan Ryan", correct: true},
				            {aid: cuid(), answer: "Roger Clemens", correct: false},
							{aid: cuid(), answer: "Tom Seaver", correct: false},
							{aid: cuid(), answer: "Dwight Gooden", correct: false}],
				  response: "On September 7, 1974, in a game against the White Sox, California Angels pitcher Nolan Ryan became the first player to break the 100 mph barrier when one of his pitches was officially clocked at 100.8 miles per hour."},
				  {qid: cuid(),
				   question: "What player was nicknamed \"Mr. November\"?",
				   answers: [{aid: cuid(), answer: "Derek Jeter", correct: true},
							  {aid: cuid(), answer: "Mariano Rivero", correct: false},
							  {aid: cuid(), answer: "Reggie Jackson", correct: false},
							  {aid: cuid(), answer: "David Ortiz", correct: false}],
					response: "New York Yankee Derek Jeter earned the nicknames \"Captain Clutch\" and \"Mr. November\" due to his outstanding play in the postseason. Throughout his career, he was a reliable contributor to the Yankees' franchise successes and has a .321 batting average in the World Series."},
					{qid: cuid(),
					question: "What famous criminal was once a professional baseball player?",
					answers: [{aid: cuid(), answer: "John Dillinger", correct: true},
							  {aid: cuid(), answer: "Ted Bundy", correct: false},
							  {aid: cuid(), answer: "Lucky Luciano", correct: false},
							  {aid: cuid(), answer: "Al Capone", correct: false}],
					response: "Like most red-blooded American boys of the time, young John Dillinger was an avid baseball fan. During the summer of 1924, he played shortstop for the Martinsville Athletics. His team-high batting average earned him a $25 award from the local Old Hickory Furniture Company."},	
					{qid: cuid(),
						question: "What Chicago Cub was nicknamed \"Mr. Sunshine\"?",
						answers: [{aid: cuid(), answer: "Ernie Banks", correct: true},
								  {aid: cuid(), answer: "Dizzy Dean", correct: false},
								  {aid: cuid(), answer: "Fred Lindstrom", correct: false},
								  {aid: cuid(), answer: "Hugh Duffy", correct: false}],
						response: "Nicknamed \"Mr. Sunshine\" for his sunny disposition, Ernie Banks played with joy and immense talent for the Cubs from 1953-71, though never making a postseason appearance. In 1958 and 1959, he won Most Valuable Player Awards and became the Cubs' first Gold Glove winner in 1960."},	
					{qid: cuid(),
					question: "How long was the shortest game in Major League Baseball history?",
					answers: [{aid: cuid(), answer: "51 minutes", correct: true},
							  {aid: cuid(), answer: "1 hour 33 minutes", correct: false},
							  {aid: cuid(), answer: "1 hour 15 minutes", correct: false},
							  {aid: cuid(), answer: "1 hour 1 minute", correct: false}],
					response: "On September 28, 1919, the New York Giants defeated the Philadelphia Phillies 6-1 in just 51 minutes."},
					{qid: cuid(),
					question: "What female pitcher once struck out Babe Ruth and Lou Gehrig?",
					answers: [{aid: cuid(), answer: "Jackie Mitchell", correct: true},
							  {aid: cuid(), answer: "Constance Morgan", correct: false},
							  {aid: cuid(), answer: "Kelsie Whitmore", correct: false},
							  {aid: cuid(), answer: "Mamie Johnson", correct: false}],
					response: "Jackie Mitchell, a 17-year-old female pitcher for the AA Chattanooga Lookouts, once played the New York Yankees in an exhibition game and struck out Babe Ruth and Lou Gehrig in succession."},
					{qid: cuid(),
					question: "What player was killed by a pitch from Yankees pitcher Carl Mays?",
					answers: [{aid: cuid(), answer: "Ray Chapman", correct: true},
							   {aid: cuid(), answer: "Tony Conigliaro", correct: false},
							   {aid: cuid(), answer: "Bryce Florie", correct: false},
							   {aid: cuid(), answer: "Herb Score", correct: false}],
					response: "On August 16, 1920, Cleveland Indians shortstop Ray Chapman was hit in the head by a pitch from Yankees pitcher Carl Mays, and died 12 hours later. His death was largely responsible for the spitball being banned after the 1920 season."}
			];
				  