"use strict"

const baseball = [{qid: cuid(),
				  question: "Which team has won the most World Series title?",
				  answers: [{aid: cuid(), answer: "New York Yankees", correct: true},
				            {aid: cuid(), answer: "Chicago White Sox", correct: false},
							{aid: cuid(), answer: "Toronto Blue Jays", correct: false},
							{aid: cuid(), answer: "Atlanta Braves", correct: false}],
				  finalText: "The Yankees have won 27 World Series titles.  Next comes the St Louis Cardinals who have won 11 followed by the Boston Red Sox with 9."},
				  {qid: cuid(),
				  question: "What famous baseball player said, \"It ain't over 'til it's over.",
				  answers: [{aid: cuid(), answer: "Yogi Berra", correct: true},
				            {aid: cuid(), answer: "Hank Aaron", correct: false},
							{aid: cuid(), answer: "Josh Gibson", correct: false},
							{aid: cuid(), answer: "Johnny Damon", correct: false}],
				  finalText: "Berra-isms (colloquial expressions that lack logic) are now countless, and many of them are just attributed to Berra, even if he never actually said them. As he so perfectly put it: \“I never said most of the things I said.\” Here are some others: When you come to a fork in the road, take it.  You can observe a lot by just watching.  It’s like déjà vu all over again.  No one goes there nowadays, it’s too crowded. Baseball is 90% mental and the other half is physical.  A nickel ain’t worth a dime anymore. Always go to other people’s funerals, otherwise they won’t come to yours."},
				  {qid: cuid(),
				  question: "Where is the Baseball Hall of Fame and National Museum located?",
				  answers: [{aid: cuid(), answer: "Cooperstown New York", correct: true},
				            {aid: cuid(), answer: "Baltimore Maryland", correct: false},
							{aid: cuid(), answer: "Cleveland Ohio", correct: false},
							{aid: cuid(), answer: "Louisville Kentucky", correct: false}],
				  finalText: "The National Baseball Hall of Fame and Museum is an American history museum operated by private interests. As of 2018, 323 players have been elected to the Hall of Fame."},
				  {qid: cuid(),
				  question: "The Red Sox sold Babe Ruth to what team in 1920?",
				  answers: [{aid: cuid(), answer: "New York Yankees", correct: true},
				            {aid: cuid(), answer: "Los Angeles Angels", correct: false},
							{aid: cuid(), answer: "Brooklyn Dodgers", correct: false},
							{aid: cuid(), answer: "Washington Senators", correct: false}],
				  finalText: "Many baseball fans believe the sale of Babe Ruth created a curse, called the \"Curse of the Bambino,\" that prevented the Red Sox from winning a World Series. The \"curse\" was finally reversed in 2004, however."},
				  {qid: cuid(),
				  question: "What father-son pair was the only to play in the major leagues at the same time?",
				  answers: [{aid: cuid(), answer: "Ken Griffey Jr and Ken Griffey Sr", correct: true},
				            {aid: cuid(), answer: "Barry and Bobby Bonds", correct: false},
							{aid: cuid(), answer: "Tito and Terry Francona", correct: false},
							{aid: cuid(), answer: "Dale and Yogi Berra", correct: false}],
				  finalText: "They were also the only father and son to play on the same team.  On September 14th, 1990, Ken Griffey Sr. hit a home run. His son, Ken Griffey Jr. stepped up to the plate next and followed up his father with his own long ball. The two became the first father and son to hit a home run in the same game."},
				  {qid: cuid(),
				  question: "Who was the only pitcher to pitch a perfect game in a World Series?",
				  answers: [{aid: cuid(), answer: "Don Larsen", correct: true},
				            {aid: cuid(), answer: "David Wells", correct: false},
							{aid: cuid(), answer: "Sandy Koufax", correct: false},
							{aid: cuid(), answer: "Dennis Martinez", correct: false}],
				  finalText: "Don Larsen of the New York Yankees pitched a perfect game during the 1956 World Series."},
				  {qid: cuid(),
				  question: "Who was the first African American baseball player to play in the modern major leagues?",
				  answers: [{aid: cuid(), answer: "Jackie Robinson", correct: true},
				            {aid: cuid(), answer: "Buck Leonard", correct: false},
							{aid: cuid(), answer: "Willie Mays", correct: false},
							{aid: cuid(), answer: "Satchel Paige", correct: false}],
				  finalText: "Jackie Robinson broke the baseball color line when he started at first base for the Brooklyn Dodgers on April 15, 1947.  He opened the door for many others and will forever be appreciated for his contribution to the game.  \“A life is not important except in the impact it has on other lives.\""},
				  {qid: cuid(),
				  question: "Which pitcher has stuck the most batters?",
				  answers: [{aid: cuid(), answer: "Nolan Ryan", correct: true},
				            {aid: cuid(), answer: "Roger Clemens", correct: false},
							{aid: cuid(), answer: "Tom Seaver", correct: false},
							{aid: cuid(), answer: "Cy Young", correct: false}],
				  finalText: "Nolan Ryan played 27 seasons in major league baseball and struck out 5714 batters."},
				  {qid: cuid(),
				  question: "What player holds the all time record number of hits?",
				  answers: [{aid: cuid(), answer: "Pete Rose", correct: true},
				            {aid: cuid(), answer: "Mark McGwire", correct: false},
							{aid: cuid(), answer: "Sammy Sosa", correct: false},
							{aid: cuid(), answer: "Alex Rodriquez", correct: false}],
				  finalText: "Pete Rose logged 4,256 hits in his career.  Next comes Ty Cobbs with 4191.  They are the only two players with more than 4000 career hits."},
				  {qid: cuid(),
				  question: "What player has won the most MVP awards?",
				  answers: [{aid: cuid(), answer: "Barry Bonds", correct: true},
				            {aid: cuid(), answer: "Stan Musial", correct: false},
							{aid: cuid(), answer: "David Ortiz", correct: false},
							{aid: cuid(), answer: "Lou Gehrig", correct: false}],
				  finalText: "Bonds has won four National League MVP Awards.  Several American League players have won three titles."}
			];
				  